# Generated by Django 4.1.5 on 2023-01-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_post_another_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('questions', models.CharField(max_length=250)),
                ('answer', models.TextField()),
            ],
        ),
    ]
